
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: library_db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - library_network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: estebangaviria82@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - library_network

networks:
  library_network:
    driver: bridge
